version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - 'direct-dependency-update'
    commit-message:
      prefix: dependabot
      include: scope
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
      - dependency-name: '@aws-sdk/*'
