version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
    target-branch: main
    labels:
      - dependabot
      - dependencies
    ignore:
      - dependency-name: 'node'
        versions: ['21.x']
    commit-message:
      prefix: BAU

  - package-ecosystem: 'docker'
    directory: '/tests'
    schedule:
      interval: daily
      time: '03:00'
    target-branch: main
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
    target-branch: main
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU
