plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.4.1.cjs

packageExtensions:
  '@aws-sdk/credential-provider-node@>=3.629.0':
    dependencies:
      '@aws-sdk/client-sts': '*'
  '@aws-sdk/credential-provider-sso@>=3.629.0':
    dependencies:
      '@aws-sdk/client-sso-oidc': '*'
      '@aws-sdk/client-sts': '*'
