export type EnvironmentVar = {
  name:
    | 'ANALYSIS_BUCKET_NAME'
    | 'AUDIT_BUCKET_NAME'
    | 'INITIATE_DATA_REQUEST_LAMBA_LOG_GROUP_NAME'
    | 'PROCESS_DATA_REQUEST_LAMBA_LOG_GROUP_NAME'
    | 'TEST_DATA_BUCKET_NAME'
    | 'ZENDESK_ADMIN_EMAIL'
    | 'ZENDESK_AGENT_EMAIL'
    | 'ZENDESK_API_KEY'
    | 'ZENDESK_BASE_URL'
    | 'ZENDESK_END_USER_EMAIL'
    | 'ZENDESK_WEBHOOK_API_BASE_URL'
    | 'ZENDESK_WEBHOOK_SECRET_KEY'
}
