export type EnvironmentVar = {
  name:
    | 'INITIATE_DATA_REQUEST_LAMBDA_LOG_GROUP_NAME'
    | 'PROCESS_DATA_REQUEST_LAMBDA_LOG_GROUP_NAME'
    | 'ZENDESK_ADMIN_EMAIL'
    | 'ZENDESK_AGENT_EMAIL'
    | 'ZENDESK_API_KEY'
    | 'ZENDESK_BASE_URL'
    | 'ZENDESK_END_USER_EMAIL'
    | 'ZENDESK_WEBHOOK_API_BASE_URL'
    | 'ZENDESK_WEBHOOK_SECRET_KEY'
    | 'INITIATE_ATHENA_QUERY_QUEUE_URL'
    | 'INITIATE_ATHENA_QUERY_LAMBDA_LOG_GROUP_NAME'
    | 'AUDIT_REQUEST_DYNAMODB_TABLE'
}
