import {
  TEST_NOTIFY_SECRET_NAME,
  TEST_ANALYSIS_BUCKET,
  TEST_AUDIT_BUCKET,
  TEST_AWS_ACCOUNT_ID,
  TEST_BATCH_JOB_MANIFEST_BUCKET_ARN,
  TEST_BATCH_JOB_MANIFEST_BUCKET_NAME,
  TEST_BATCH_JOB_ROLE_ARN,
  TEST_ZENDESK_FIELD_DATA_PATHS,
  TEST_ZENDESK_FIELD_DATE_FROM,
  TEST_ZENDESK_FIELD_DATE_TO,
  TEST_ZENDESK_FIELD_EVENT_IDS,
  TEST_ZENDESK_FIELD_IDENTIFIER_TYPE,
  TEST_ZENDESK_FIELD_JOURNEY_IDS,
  TEST_ZENDESK_FIELD_PII_TYPES,
  TEST_ZENDESK_FIELD_SESSION_IDS,
  TEST_ZENDESK_FIELD_USER_IDS,
  TEST_ZENDESK_SECRET_NAME
} from '../testConstants'

import { MOCK_INITIATE_DATA_REQUEST_QUEUE_URL } from '../testConstants'

process.env.ANALYSIS_BUCKET_NAME = TEST_ANALYSIS_BUCKET
process.env.AUDIT_BUCKET_NAME = TEST_AUDIT_BUCKET
process.env.AWS_REGION = 'eu-west-2'
process.env.ATHENA_DATABASE_NAME = 'test_database'
process.env.ATHENA_TABLE_NAME = 'test_table'
process.env.DYNAMODB_TABLE_NAME = 'test_query_table'
process.env.ZENDESK_API_SECRETS_NAME = TEST_ZENDESK_SECRET_NAME
process.env.NOTIFY_API_SECRETS_NAME = TEST_NOTIFY_SECRET_NAME
process.env.INITIATE_DATA_REQUEST_QUEUE_URL =
  MOCK_INITIATE_DATA_REQUEST_QUEUE_URL
process.env.BATCH_JOB_MANIFEST_BUCKET_ARN = TEST_BATCH_JOB_MANIFEST_BUCKET_ARN
process.env.BATCH_JOB_MANIFEST_BUCKET_NAME = TEST_BATCH_JOB_MANIFEST_BUCKET_NAME
process.env.ACCOUNT_ID = TEST_AWS_ACCOUNT_ID
process.env.BATCH_JOB_ROLE_ARN = TEST_BATCH_JOB_ROLE_ARN
process.env.ZENDESK_FIELD_DATA_PATHS = TEST_ZENDESK_FIELD_DATA_PATHS
process.env.ZENDESK_FIELD_DATE_FROM = TEST_ZENDESK_FIELD_DATE_FROM
process.env.ZENDESK_FIELD_DATE_TO = TEST_ZENDESK_FIELD_DATE_TO
process.env.ZENDESK_FIELD_EVENT_IDS = TEST_ZENDESK_FIELD_EVENT_IDS
process.env.ZENDESK_FIELD_IDENTIFIER_TYPE = TEST_ZENDESK_FIELD_IDENTIFIER_TYPE
process.env.ZENDESK_FIELD_JOURNEY_IDS = TEST_ZENDESK_FIELD_JOURNEY_IDS
process.env.ZENDESK_FIELD_PII_TYPES = TEST_ZENDESK_FIELD_PII_TYPES
process.env.ZENDESK_FIELD_SESSION_IDS = TEST_ZENDESK_FIELD_SESSION_IDS
process.env.ZENDESK_FIELD_USER_IDS = TEST_ZENDESK_FIELD_USER_IDS
