import { getEnv } from '../utils/helpers'

export const AWS_REGION = 'eu-west-2'
export const INITIATE_DATA_REQUEST_LAMBDA_LOG_GROUP = getEnv(
  'INITIATE_DATA_REQUEST_LAMBDA_LOG_GROUP_NAME'
)
export const PROCESS_DATA_REQUEST_LAMBDA_LOG_GROUP = getEnv(
  'PROCESS_DATA_REQUEST_LAMBDA_LOG_GROUP_NAME'
)
export const AUDIT_REQUEST_DYNAMODB = getEnv('AUDIT_REQUEST_DYNAMODB_TABLE')
export const INITIATE_ATHENA_QUERY_LAMBDA_LOG_GROUP = getEnv(
  'INITIATE_ATHENA_QUERY_LAMBDA_LOG_GROUP_NAME'
)
export const INITIATE_ATHENA_QUERY_QUEUE_URL = getEnv(
  'INITIATE_ATHENA_QUERY_QUEUE_URL'
)
