import { getEnv } from '../utils/helpers'

export const ZENDESK_PII_FORM_ID = 5603412248860
export const PII_FORM_IDENTIFIER_FIELD_ID = 5605352623260
export const PII_FORM_IDENTIFIER_EVENT_ID_FIELD_ID = 5605423021084
export const PII_FORM_REQUEST_DATE_FIELD_ID = 5605700069916
export const PII_FORM_REQUESTED_PII_TYPE_FIELD_ID = 5641719421852
export const PII_FORM_CUSTOM_DATA_PATH_FIELD_ID = 5698447116060
export const PII_FORM_REQUEST_STATUS_FIELD_ID = 5605885870748
export const PII_FORM_IDENTIFIER_RECIPIENT_EMAIL = 6202354485660
export const PII_FORM_IDENTIFIER_RECEIPIENT_NAME = 6202301182364

export const ZENDESK_ADMIN_EMAIL = getEnv('ZENDESK_ADMIN_EMAIL')
export const ZENDESK_AGENT_EMAIL = getEnv('ZENDESK_AGENT_EMAIL')
export const ZENDESK_END_USER_EMAIL = getEnv('ZENDESK_END_USER_EMAIL')
export const ZENDESK_END_USER_NAME = 'Txma-team2-ticf-analyst-dev'

export const ZENDESK_BASE_URL = getEnv('ZENDESK_BASE_URL')
export const ZENDESK_REQUESTS_ENDPOINT = '/api/v2/requests'
export const ZENDESK_TICKETS_ENDPOINT = '/api/v2/tickets'

export const ZENDESK_WEBHOOK_API_BASE_URL = getEnv(
  'ZENDESK_WEBHOOK_API_BASE_URL'
)
export const ZENDESK_WEBHOOK_SECRET_KEY = getEnv('ZENDESK_WEBHOOK_SECRET_KEY')
