#!/usr/bin/env sh

npx lint-staged

git diff --cached --name-only | if grep --quiet template.yaml
then
  echo "\nRunning Checkov hook...\n"
  checkov -d . --framework cloudformation --quiet --skip-check CKV_AWS_116
fi
